_admin_domain:
  resource: "@HolloBindBundle/Controller/AdminDomainController.php"
  type:     annotation
  prefix:   /admin

_domain:
  resource: "@HolloBindBundle/Controller/DomainController.php"
  type:     annotation

_record:
  resource: "@HolloBindBundle/Controller/RecordController.php"
  type:     annotation
