<?php

namespace Hollo\BindBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HostQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostQueueRepository extends EntityRepository
{
  public function findQueued($hostname)
  {
    $query =
      "SELECT ".
        "mq ".
      "FROM ".
        "HolloBindBundle:ModQueue mq LEFT JOIN ".
        "mq.host_queue hq WITH ".
        "hq.host = :host ".
      "WHERE ".
        "hq.completed IS NULL";

    return $this->_em
      ->createQuery($query)
      ->setParameters(array(
        'host' => $hostname
      ))
      ->getResult();
  }
}
