<?php

namespace Hollo\BindBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LockRepository extends EntityRepository
{
}
